# Generated by Django 2.1.3 on 2018-12-03 19:49

from django.db import migrations
import polls.managers


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', polls.managers.UserManager()),
            ],
        ),
    ]
