# Generated by Django 2.1.3 on 2018-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo_barras', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('Tienda', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('img', models.ImageField(blank=True, upload_to='images/productos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
            },
        ),
    ]
