# Generated by Django 2.1.3 on 2018-12-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
