# Generated by Django 2.1.3 on 2018-12-04 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_producto_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('CodigoFactura', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('Vendido', models.BooleanField(default=False)),
                ('Codigo_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Producto')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
