# Generated by Django 2.1.3 on 2018-12-04 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('idbusqueda', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'busqueda',
                'verbose_name_plural': 'busquedas',
            },
        ),
    ]
